#PROD SERVER
#스마투스 프리미엄 앱 (학교구독 서비스) 
spring:
    profiles:
        active: prod


    #datasource (mariaDB)
    datasource:
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        #운영서버 Prod Database (ADMIN)
        db-url: jdbc:log4jdbc:mariadb://smartooth-database.cdx8q9adtw2b.ap-northeast-2.rds.amazonaws.com:3306/Smartooth
        #db-url: jdbc:log4jdbc:mariadb://smartooth-prod-database.cdx8q9adtw2b.ap-northeast-2.rds.amazonaws.com:3306/Smartooth
        db-username: smartooth
        db-password: smartooth509#

        
    mvc:
        view:
            prefix: /WEB-INF/views/
            suffix: .jsp
        static-path-pattern : /static/**

        
    #메일 발송 부분은 로직은 동일, 메일 발송 HOST, ID, 비밀번호만 변경해주면 됨
    mailsendername: Smartooth KOREA
    mailusername: manager@smartooth.co
    mailpassword: dkagh1505!@
  
  
    mybatis:
        configuration:
            map-underscore-to-camel-case: 'true'


    jwt:
        secretKey: tmakxntmzhfldk
        
        
    web:
        resources:
            static-locations : classpath:/static-location/

server:
    #운영 Prod (AWS)
    ip: 13.124.37.209
    port: 8090

            
#---
#spring:
#    web:
#        resources:
#            add-mappings: 'true'